buildCommand: |
  rm -rf backend/node_modules backend/package-lock.json
  npm install --prefix backend
  npm install --prefix frontend
  npm run build --prefix frontend
startCommand: npm run start --prefix backend
